site_name: 经济统计指南
site_description: 经济统计学习指南与资源
site_author: butforyou
site_url: https://butforyou.github.io/a-guide-of-economic-statistics/

theme:
  name: material
  palette:
    primary: blue
    accent: light blue
  features:
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - search.suggest
    - search.highlight

# 插件
plugins:
  - search

# 页面导航
nav:
  - 序: index.md
  - 必要工具: chapter6.md
  - 概率论与数理统计: chapter1.md
  - 机器学习: chapter2.md
  - 深度学习与计算机视觉: chapter3.md
  - 推荐系统: chapter4.md
  - Python 编程基础: chapter5.md
  

# 扩展
markdown_extensions:
  - admonition
  - codehilite
  - extra
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.superfences

# 版权信息
copyright: Copyright &copy; 2024 butforyou